export const SQUARE = Object.freeze({
  WPAWN: 0, WKNIGHT: 1, WBISHOP: 2, WROOK: 3, WQUEEN: 4, WKING: 5,
  BPAWN: 6, BKNIGHT: 7, BBISHOP: 8, BROOK: 9, BQUEEN: 10, BKING: 11,
  EMPTY: 12
});

export const baseBoardBlack: Int8Array = new Int8Array([
  SQUARE.WROOK, SQUARE.WKNIGHT, SQUARE.WBISHOP, SQUARE.WQUEEN,
  SQUARE.WKING, SQUARE.WBISHOP, SQUARE.WKNIGHT, SQUARE.WROOK,
  ...Array(8).fill(SQUARE.WPAWN),
  ...Array(32).fill(SQUARE.EMPTY),
  ...Array(8).fill(SQUARE.BPAWN),
  SQUARE.BROOK, SQUARE.BKNIGHT, SQUARE.BBISHOP, SQUARE.BQUEEN,
  SQUARE.BKING, SQUARE.BBISHOP, SQUARE.BKNIGHT, SQUARE.BROOK,
])

export const baseBoardWhite: Int8Array = new Int8Array([
  SQUARE.BROOK, SQUARE.BKNIGHT, SQUARE.BBISHOP, SQUARE.BQUEEN,
  SQUARE.BKING, SQUARE.BBISHOP, SQUARE.BKNIGHT, SQUARE.BROOK,
  ...Array(8).fill(SQUARE.BPAWN),
  ...Array(32).fill(SQUARE.EMPTY),
  ...Array(8).fill(SQUARE.WPAWN),
  SQUARE.WROOK, SQUARE.WKNIGHT, SQUARE.WBISHOP, SQUARE.WQUEEN,
  SQUARE.WKING, SQUARE.WBISHOP, SQUARE.WKNIGHT, SQUARE.WROOK,
])
