name: CI/CD pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test run
      uses: actions/checkout@v4
      run: |
        make deploy
        python3 ./tests/startup.py
